{"name": "test_c", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1\n  +2\n  -1", "trace": "self = <test_a.Test1 object at 0x04506A30>\n\n    @pytest.mark.flaky(reruns=5, reruns_delay=2)\n    def test_c(self):\n>       assert 2==1\nE       assert 2 == 1\nE         +2\nE         -1\n\ntest_a.py:21: AssertionError"}, "start": 1602494369380, "stop": 1602494369380, "uuid": "cfee7be6-9621-49ca-94cb-0630ebf893fb", "historyId": "9def8b0efd7baa2665871196d4306c53", "testCaseId": "84b72733866ef5fc345f1803b40196ea", "fullName": "test_a.Test1#test_c", "labels": [{"name": "suite", "value": "test_a"}, {"name": "subSuite", "value": "Test1"}, {"name": "host", "value": "LAPTOP-RVJBHD5J"}, {"name": "thread", "value": "27356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_a"}]}